export type Project = {
  id: string; category: '/automation' | '/data-engineering' | '/llm-evaluation';
  label: string; title: string; description: string; tools: string;
  metric?: string; unit?: string; result?: string; decision?: string;
  claim?: string; diagram?: string; related?: string; href?: string;
};

export const projects: Project[] = [
  {id:'polls', category:'/automation', label:'Workflow automation / Product', title:'A survey workflow someone else could run', description:'Running a survey meant working through a long checklist across several tools and teams. I built a guided pipeline that handles the system changes and asks the operator to approve each stage.', metric:'4', unit:'human approval gates', result:'A first-time operator completed setup and build with zero manual system edits.', decision:'I had to decide which steps the pipeline could handle on its own. System changes are automated, but the workflow waits for a person to approve the decisions before continuing.', tools:'Python · APIs · Claude Code', claim:'poll.first-time-operator', diagram:'flow'},
  {id:'data', category:'/data-engineering', label:'Data engineering / Analytics', title:'Maintaining a shared validation engine', description:'The research practices had nearly identical validation scripts that were getting hard to maintain. I replaced them with a shared engine. Adding a practice now means updating its configuration.', metric:'8', unit:'research practices', result:'The engine surfaces roughly 200 data-quality flags per full refresh cycle, based on my own estimate.', decision:'I kept member data out of the AI coding workflow. The model saw only structure and aggregate diagnostics, and I used synthetic data to check the code. Comparing the results with a colleague’s manual count uncovered a join bug.', tools:'Python · Data validation · Synthetic fixtures', claim:'benchmark.script-consolidation', diagram:'matrix'},
  {id:'publishing', category:'/automation', label:'API integration / Validation', title:'Checking author matches before going live', description:'The conference-to-CMS integration needed to attach the right authors to each session. Before writing anything live, I checked its matches against archived sessions that people had linked by hand.', metric:'58/61', unit:'exact author matches', result:'I accounted for every mismatch and checked the full content sync in a test environment before writing to production.', decision:'I needed a way to check the mapping beyond looking through the output. The archived sessions gave me a reference set, so I could investigate each disagreement before going live.', tools:'Cvent · Contentful · API integration', claim:'cms.author-mapping-validation', diagram:'mapping'},
  {id:'indices', category:'/data-engineering', label:'Data engineering / Analytics', title:'Owning a quarterly financial-data pipeline', description:'I took over a recurring financial-index refresh and moved it from manual CalcBench entry into an API-driven Alteryx pipeline feeding BigQuery.', metric:'Quarterly', unit:'refresh ownership', result:'The work included the refresh itself, data-quality checks, documentation, and outlier detection in Tableau.', decision:'The pipeline still needed someone to check the data each quarter. I owned that process alongside the migration, so the automation and the checks were maintained together.', tools:'Alteryx · BigQuery · Tableau · APIs', claim:'indices.scope-and-longevity', diagram:'pipeline'},
  {id:'evaluation', category:'/llm-evaluation', label:'AI engineering / Research', title:'AI judging panel', description:'I built an AI judging panel and compared its judgments with human experts. I also tested whether its evaluator was rewarding sound judgment.', tools:'LLM evaluation · Python · Study design', href:'/llm-evaluation/ai-judging-panel'},
  {id:'handoff', category:'/automation', label:'Operator tools / Documentation', title:'Making AI workflows easier to hand off', description:'I packaged workflows with reusable skills, configuration files, runbooks, and handoff notes so another operator could pick up the work.', decision:'The documentation needed to explain where to start, which decisions needed a person, and how to recover when a step failed.', tools:'Claude Code · Skills · YAML · Runbooks', related:'Cross-project handoff framework'},
  {id:'instrument-browser', category:'/data-engineering', label:'Data access / Research tools', title:'A read-only research instrument browser', description:'I built a tool for browsing published benchmark instruments, filtering questions, and exporting modules to Excel.', decision:'I used a read-only API so a colleague could explore the instrument without the tool being able to change the source content.', tools:'Python · Contentful · Excel', related:'Part of the benchmark platform'},
  {id:'instrument-loader', category:'/data-engineering', label:'Data updates / Content operations', title:'Updating benchmark instruments from spreadsheets', description:'I built a write-enabled tool that creates or updates question, practice, and metric definitions in the CMS from Excel, with a result log for each row.', tools:'Python · Excel · Contentful', related:'Part of the benchmark platform'},
  {id:'survey-publishing', category:'/automation', label:'Content automation / AI-assisted drafting', title:'Turning survey results into CMS drafts', description:'I built an Alteryx workflow that transforms survey results, generates draft captions and an executive summary, and sends the content to the CMS for review.', decision:'I kept the workflow in Alteryx so it fit the existing process. AI-generated text stayed in drafts for a person to review.', tools:'Alteryx · Alchemer · OpenAI API · Contentful'},
  {id:'speaker-intake', category:'/automation', label:'Intake automation / Data cleaning', title:'Moving speaker submissions into ClickUp', description:'I replaced an Alteryx intake workflow with Python scripts that clean survey responses and map them to ClickUp fields.', tools:'Python · Alchemer · ClickUp'},
  {id:'survey-styling', category:'/automation', label:'Frontend troubleshooting / Reusable skills', title:'Making survey styling work in Alchemer', description:'I traced the survey platform’s DOM and stylesheet loading order to find where custom styles would stick, then packaged the approach as a reusable skill.', decision:'The design had to work inside the platform’s existing markup. Inspecting the actual form was more useful than designing a mockup the platform could not support.', tools:'CSS · Chrome DevTools · Claude skills'},
  {id:'clickup-fields', category:'/automation', label:'API tooling / Workflow support', title:'Managing ClickUp custom fields', description:'I built scripts to create, copy, and update custom-field schemas across ClickUp lists, alongside a survey-response sync.', tools:'Python · ClickUp API · Alchemer', related:'Supporting tooling for intake workflows'},
  {id:'meeting-tasks', category:'/automation', label:'Conversational automation', title:'Turning meeting notes into tasks', description:'I created conversational skills that turn meeting notes into ClickUp tasks.', tools:'Claude Code skills · ClickUp'},
  {id:'poll-reporting', category:'/data-engineering', label:'Reporting / Survey tools', title:'Poll reports and survey dashboards', description:'I created skills for preparing poll results reports and survey dashboards as part of the survey workflow.', tools:'Claude Code skills · Survey reporting', related:'Part of the poll lifecycle'},
];
